### ISSUE TITLE
When uploading data to the firebase this error is showing

### ISSUE THREAD

**Issue by Naseeb-Nex** [Naseeb-Nex/Ideal-maketing-app#1]
These are the errors

```
I/flutter (30601): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
```

**Comment by faizanMayo786** [comment]
you are calling setState in a stream or you may be using setState while the firebase is also using setState.

**Comment by Naseeb-Nex** [comment]
> you are calling setState in a stream or you may be using setState while the firebase is also using setState.

How to solve it.
any idea.... 💡

**Comment by faizanMayo786** [comment]
Without reviewing code its difficult to tell

**Comment by Naseeb-Nex** [comment]
> Without reviewing code its difficult to tell

Am new here How to share the code here?

**Comment by faizanMayo786** [comment]
you can send the code snippet

**Comment by Naseeb-Nex** [comment]
> you are calling setState in a stream or you may be using setState while the firebase is also using setState.

Find it and resolved it. Thanks 🤝
