### ISSUE TITLE
How do the proper way to update data to the firebase and showing a loading in dialog box then return to home screen?

### ISSUE THREAD

**Issue by Naseeb-Nex** [Naseeb-Nex/Ideal-maketing-app#2]
I am updating data with await keywords. after all firebase data updating code
place the Navigator.push( ..... );
is this the correct way? 

Also needed a Circular Progress Indicator.

**Comment by faizanMayo786** [comment]
yes, you can await if the app has security factors. You can make a loader variable and change its value as true or false then apply conditional rendering according to the loader variable

**Comment by Naseeb-Nex** [comment]
> yes, you can await if the app has security factors. You can make a loader variable and change its value as true or false then apply conditional rendering according to the loader variable

I have multiple firebase updates in a single function so which is the common method that in this situation?

**Comment by faizanMayo786** [comment]
In my opinion, do this: make a loader variable and change its value as true or false then apply conditional rendering according to the loader variable

**Comment by Naseeb-Nex** [comment]
> In my opinion, do this: make a loader variable and change its value as true or false then apply conditional rendering according to the loader variable

Thanks, for the help 🤝
My doubt is cleared. Your support is very helpful to me... 
😊
